### ISSUE TITLE
No other way to contact you, blog comments don't work 😅

### ISSUE THREAD

**Issue by seanhagen** [naiveai/adventofcode#2]
I tried to leave this comment on your [blog post on learning Rust in 2023](https://naiveai.hashnode.dev/learning-rust-in-2023-a-call-for-discussion), but wasn't able to -- so instead I'm doing this! 😅 

Couldn't figure out why I couldn't post the comment, I wasn't seeing any error messages or anything ( either in the page or in the browser inspector 😑 ).

Comment reproduced here:

I've been trying to learn Rust for a few weeks now, on and off. It's "on and off" because so far, every time, I run into something that makes me frustrated enough to not want to touch Rust for a little while.

Good example: spent today trying to learn how to use Rust on embedded devices. Specifically, an Adafruit Neo Trinkey, using the atsamd-rs/atsamd crate that supports it. I spent two hours trying to understand why "my" code ( both the src/main.rs & Cargo.toml were copied from the example ) wouldn't upload, but the example in the atsamd-rs/atsamd repo would. Googling turned up nothing, no results that would explain why. 

Turns out, I needed some special config in .cargo/config. Something that as far as I can tell is only covered briefly in the Embedded Rust book -- and even there it doesn't give a full example of what should be in the config. The atsamd-rs/atsamd README makes NO mention of needing this config, which is why it took so long to figure this out.

Even worse, the quickstart example given in the Embedded Rust to use with "cargo generate" still didn't work for me because I'm not using the exact device they use in the book. I ended up having to replace it with the .cargo/config from the atsamd-rs/atsamd repo anyways to get it to work. 

I wanted to start the way I do with every other language and every other hobby project: fooling around to try and get a feel for things. But at the end of the day it felt like my only options were to do things exactly as they do in the book ( meaning buy a microcontroller dev board I may never use again ) or to give up. 

The kicker for me was the incredibly unhelpful error messages when trying to compile. How does ```"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidBinary'```" help me, especially when there are NO RESULTS on Google for that. C/C++ might have byzantine error messages sometimes, but at least they make things pretty clear in comparison. I think part of the issue was also that using Cargo to build hides a lot of status/log stuff, making it hard to understand exactly where things were breaking down.

I found a post (https://kevinlynagh.com/rust-zig/) while Googling that makes a good point: it feels like all the various parts of Rust are disjointed -- learning one thing doesn't help you learn or understand any other part of the language. It also doesn't help that the disjoint parts of the language don't have any clear markers that let you know if you NEED to learn them or not. 

Maybe it's the verbosity of the language, but I don't feel like Rust has ANY signposts that let me know what's safe to ignore, or when I should start learning a new concept. It feels like I'm being sat down at a giant table covered in tools and told I need to learn all of them before I can even think of doing some basic woodworking.

It feels like a language designed for people who like reading technical manuals from start to finish before they start a hobby project using something new.

**Comment by naiveai** [comment]
Thanks for the interesting feedback! I'm collating all of it into a new article soon. It's interesting that the comments don't work for you, I can't figure out why that would be.
